### ISSUE TITLE
Actualización automática de la orden al interactuar con los botones TransitionButton y DDL

### ISSUE THREAD

**Issue by FacuMasino** [FacuMasino/tpc-equipo-16#1]
### Descripción del problema:

Actualmente, cuando hacemos clic en los botones TransitionButton de una orden o interactuamos con el DropdownList para cambiar el estado de una orden, la información de la orden no se actualiza automáticamente en la interfaz. En lugar de eso, es necesario realizar una actualización manual de la página (presionando F5) para ver los cambios reflejados.

### Pasos para reproducir el problema:

Navega a la página de una orden en el panel de administración del ecommerce.
Haz clic en cualquier botón TransitionButton para cambiar el estado de la orden.
Alternativamente, utiliza el DropdownList para seleccionar un nuevo estado para la orden.
Observa que la información de la orden no se actualiza automáticamente en la interfaz.
Comportamiento esperado:

La información de la orden debería actualizarse automáticamente en la interfaz sin necesidad de realizar una actualización manual de la página (F5) cada vez que se cambie el estado de la orden o se haga clic en los botones TransitionButton.

### Sugerencia para la solución:

Implementar un UpdatePanel

**Comment by mrmalvicino** [comment]
Resuelto en 81b8c344b6efc2a0431f962a8e09ed1419cf877d
