### ISSUE TITLE
Restricción de visibilidad DDL de estado de orden

### ISSUE THREAD

**Issue by FacuMasino** [FacuMasino/tpc-equipo-16#2]
### Descripción del problema:

Actualmente, el DropdownList para forzar el estado de una orden en el Panel de Admin es visible y accesible para todos los usuarios, independientemente de su rol. Sin embargo, este control debería ser accesible únicamente por los usuarios con rol de Administrador para evitar modificaciones no autorizadas en el estado de las órdenes.

### Pasos para reproducir el problema:

- Inicia sesión en el sistema con un rol que no sea Administrador (por ejemplo Editor)
- Navega a la página de una orden en el panel de administración del ecommerce.
- Observa que el DropdownList para cambiar el estado de la orden está visible y accesible.

### Comportamiento esperado:

El DropdownList para forzar el estado de una orden debería ser visible y accesible solo para los usuarios con rol Administrador. Para los usuarios con roles distintos, el DropdownList debería estar oculto o deshabilitado

**Comment by mrmalvicino** [comment]
Solucionado en commit 030e00296c2947185ed8d8a929dc1a476d357a04
