### ISSUE TITLE
Activar autopostback para el cambio de rol en Panel Admin

### ISSUE THREAD

**Issue by FacuMasino** [FacuMasino/tpc-equipo-16#4]
### Descripción del problema:

En la sección de administración de usuarios, los botones utilizados para editar el estado de los usuarios no reflejan inmediatamente el cambio de estado en la interfaz. Actualmente, es necesario refrescar la página manualmente para que los botones actualicen su color y muestren el rol activo del usuario.

### Características deseadas:

- Autopostback activado: Los botones de estado en la sección de administración de usuarios deben tener el autopostback activado (true), de modo que al hacer clic en un botón para cambiar el estado del usuario, el cambio se refleje automáticamente en la interfaz.
- Actualización en tiempo real: Los botones deben cambiar de color o de estado para indicar el tipo de rol activo sin requerir una actualización manual de la página.
- Feedback visual: Proporcionar una indicación visual clara sobre el rol activo del usuario mediante el cambio de color o de diseño de los botones.

### Sugerencia para la solución:

Configurar el autopostback en true para los botones de estado en la sección de administración de usuarios, asegurando que los cambios en el estado se reflejen automáticamente en la interfaz sin necesidad de recargar la página. También, considerar agregar una animación o efecto visual para mejorar la experiencia del usuario y proporcionar una retroalimentación clara.

**Comment by mrmalvicino** [comment]
Resuelto en ed4660773fdd7b5de7da198fac8562dbe717d5ca
