### ISSUE TITLE
Añadir tooltips emergentes en los botones con íconos de rol de usuario

### ISSUE THREAD

**Issue by FacuMasino** [FacuMasino/tpc-equipo-16#5]
### Descripción del problema:

Actualmente, los botones que muestran los íconos del rol de usuario en la sección de administración no proporcionan información adicional sobre el rol del usuario cuando se pasa el cursor sobre ellos. Para mejorar la usabilidad y proporcionar más información a los administradores, se debe implementar un tooltip emergente utilizando la propiedad title en estos botones. Este tooltip debería mostrar el nombre del rol o una descripción breve

**Comment by mrmalvicino** [comment]
Implementado en e06ee93f377b2036b7300adeb7b16a0c1512d8c7
