### ISSUE TITLE
Restricción de Acceso para Roles "Transportista" y "Atención al Cliente"

### ISSUE THREAD

**Issue by FacuMasino** [FacuMasino/tpc-equipo-16#6]
### Descripción del Problema:

En el panel de administración del ecommerce, actualmente los usuarios con el rol "Transportista" y "Atención al Cliente" tienen acceso a todas las opciones del panel. Sin embargo, según los requerimientos del sistema, estos roles solo deberían tener acceso a la sección de "Orders.aspx".

### Comportamiento Esperado:

- Rol "Transportista": Debería tener acceso únicamente a la sección de "Orders.aspx" en el panel de administración.
- Rol "Atención al Cliente": También debería tener acceso únicamente a la sección de "Orders.aspx" en el panel de administración.

### Sugerencias para la Solución:

1. Revisión del Control de Acceso

    - Verificar y actualizar la lógica de control de acceso en el código para asegurar que los roles "Transportista" y "Atención al Cliente" solo puedan acceder a "Orders.aspx".

3. Configuración en el Backend:

    - Asegurarse de que las restricciones de acceso también estén correctamente implementadas en el backend, posiblemente en los controladores o servicios responsables de la gestión de roles y permisos.

**Comment by mrmalvicino** [comment]
Resuelto en e0f987f355657c8758dcdb5bd1536ad25dab5cdd
